
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"user@user.fr",
    "password":"user"
}


# POST http://localhost:5000/auth/register
# Content-Type: application/json

# {
#     "email":"user2@user.fr",
#     "password":"user"
# }